config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"

  resources :warehouse_products
  resources :products
  resources :warehouses do
    get 'add_item_count'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :warehouse_products, inverse_of: :product, dependent: :destroy
  has_many :warehouses, through: :warehouse_products

  accepts_nested_attributes_for :warehouse_products, allow_destroy: true, reject_if: proc { |a| a['product_id'].blank? }

  validates_uniqueness_of :sku_code
  validates_length_of :sku_code, is: 8, message: 'should be equal to 8'
  validates_presence_of :sku_code
  validates_presence_of :name
  validates_presence_of :price

  def set_defaults
    self.sku_code ||= generate_sku
  end

  def generate_sku(sku = [])
    length = 5
    alphabets = [*'A'..'Z']
    numbers = [*'0'..'9']

    sku_characters = %w(I M 9)

    length.times do |i|
      if i % 2 == 0
        sku_characters.push(alphabets.sample)
      else
        sku_characters.push(numbers.sample)
      end
    end

    sku = sku_characters.join
    return sku
  end

  def code_length
    if sku_code.present? && (sku_code.length < 8 || sku_code.length > 8)
      errors.add(:sku_code, 'must be 8 digit')
    end
  end

end

app/models/warehouse.rb
class Warehouse < ApplicationRecord

  has_many :warehouse_products, dependent: :destroy
  has_many :products, through: :warehouse_products

  validates_uniqueness_of :wh_code
  validates_length_of :wh_code, in: 4..16, message: "should be in range between 4 to 12"
  validates_presence_of :wh_code
  validates_presence_of :name
  validates_presence_of :max_capacity
  validates_presence_of :pincode
  accepts_nested_attributes_for :warehouse_products, allow_destroy: true, reject_if: proc { |a| a['product_id'].blank? }
  after_initialize :set_defaults, if: :new_record?

  def set_defaults
    self.threshold ||= 10
    self.count ||= 0
  end

  def code_length
    if wh_code.present? && (wh_code.length < 4 || wh_code.length > 16)
      errors.add(:wh_code, 'must be 8 digit')
    end
  end


end

app/models/warehouse_product.rb
class WarehouseProduct < ApplicationRecord
  belongs_to :product
  belongs_to :warehouse
  validates :product, presence: true

  validates_uniqueness_of :product_id, scope: :warehouse_id
  validates :threshold, presence: true
  validates :item_count, presence: true


  after_initialize :set_defaults, if: :new_record?

  def set_defaults
    self.threshold ||= 10
  end


  def low_item_threshold?
    if self.item_count.present?
      if ((self.item_count == 0) || (self.item_count < self.threshold))
        self.update_attributes(low_item_threshold: true)
      else
        self.update_attributes(low_item_threshold: false)
      end
    end
  end

  def to_s
    self.product.name if self.product.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    if params[:search].present?
      search = params[:search]['name']
      @products = Product.where("name LIKE ?", "%" + search + "%").or(Product.where("sku_code LIKE ?", "%" + search + "%"))
                     .order('created_at').page(params[:page]).per(10)
    else
      @products = Product.order('created_at').page(params[:page]).per(10)
    end
    @warehouses = Warehouse.all
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      warehouses = params[:product]['warehouse_products_attributes']
      if warehouses.present?
        warehouses.each do |key, value|
          warehouse = Warehouse.where(id: value['warehouse_id'].to_i).first_or_initialize
          warehouse.threshold = value['threshold']
          warehouse.count = value['item_count']
          warehouse.save
        end
      end
      redirect_to products_path
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product Updated Successfully' }
        format.json { render :index, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @product.present?
      @product.destroy
    end
  end

  private

  def product_params
    params.require(:product).permit(
        :sku_code,
        :name,
        :price,
        warehouse_products_attributes: [:id, :product_id, :warehouse_id, :threshold, :item_count, :low_item_threshold, :_destroy]
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/warehouse_products_controller.rb
class WarehouseProductsController < ApplicationController
  def index
    @warehouse_products = WarehouseProduct.order('created_at').page(params[:page]).per(10)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:edit, :update, :show, :destroy]

  def index
    @warehouses = Warehouse.order('created_at').page(params[:page]).per(10)
  end

  def new
    @warehouse = Warehouse.new()
  end

  def edit

  end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to warehouse_path(@warehouse)
    else
      render 'edit'
    end
  end

  def show
    @warehouse_products = @warehouse.warehouse_products.order('created_at').page(params[:page]).per(15)
  end

  def add_item_count
    @warehouse = @warehouse.warehouse_products
  end


  def destroy
    if @warehouse.present?
      if @warehouse.destroy
        redirect_to products_path
      else
        render 'new'
      end
    end
  end

  def create
    @warehouse= Warehouse.new(warehouse_params)
    respond_to do |format|
      if @warehouse.save
        warehouse_product = WarehousProductCreation.new(@warehouse).call
        format.html { redirect_to @warehouse, notice: 'Warehouse was successfully created.' }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end

  end


  private

  def warehouse_params
    params.require(:warehouse).permit(
        :wh_code,
        :name,
        :pincode,
        :max_capacity,
        warehouse_products_attributes: [:id, :product_id, :warehouse_id, :item_count, :low_item_threshold, :threshold, :_destroy]
    )
  end

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_helper.rb
module DisplayHelper

  def status_color(number)
    case
    when number < 10
      'danger'
    when (number >= 10 && number <= 1000)
      'info'
    else
      ''
    end
  end

  def format_badge(text, color)
    if text.to_i != nil
      content_tag :span, class: "badge badge-wrap text-uppercase badge-#{color}" do
        content_tag :strong, text.to_i
      end
    end
  end

  def status_badge(number)
    format_badge(number, status_color(number)) if number
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMS</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand font-weight-bold text-size">IMS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', products_path, class: 'navbar-brand' %>
      </li>
      <li class="nav-item">
        <%= link_to ' New Warehouse', new_warehouse_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Product List', products_path, class: 'dropdown-item' %>
          <%= link_to 'Warehouse List', warehouses_path, class: 'dropdown-item' %>
          <%= link_to 'Warehouse Products lists', warehouse_products_path, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
    <%= render 'shared/snippets/search' %>
  </div>
</nav>
<div class="container-fluid">
  <div class="row justify-content-center">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-warning alert-dismissible fade show mt-3 alert-box" role="alert">
        <%= message %>
        <button class="close" data-dismiss="alert" aria-label="Close">
          <i class="fa fa-close"></i>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </div>
</div>
</body>
<!--<footer class="page-footer bg-dark">-->

<!--   Copyright -->
<!--  <div class="card bg-dark text-white">-->
<!--  <div class="footer-copyright text-center py-3">© 2020 Copyright:-->
<!--    <a href="https://github.com/sakshi3126"> Github</a>-->
<!--  </div>-->
<!--  </div>-->
<!--   Copyright -->

<!--</footer>-->
</html>

app/views/products/_form.html.erb
<div class="col-lg-10 mt-5">
  <section class="mb-3 pt-3 pt-lg-5 pb-2">
    <%= simple_form_for([@product], url: product_path(@product)) do |f| %>
      <% if f.object.errors.any? %>
        <ul class="list-group text-danger mb-3">
          <% f.object.errors.full_messages.each do |message| %>
            <li class="list-group-item"><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="card">
        <div class="card-header">
          <div class="page-header text-center text-black-50">
            <h2>Products Edit</h2>
          </div>
        </div>

        <div class="card-body">
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.input :sku_code, input_html: {class: 'form-control'} %>
            </div>
            <div class="form-group col-md-6">
              <%= f.input :name, input_html: {class: 'form-control'} %>
            </div>
          </div>
          <div class="form-group">
            <%= f.input :price, input_html: {class: 'form-control'}, value: f.object.price %>
          </div>
          <br>
          <div class="border-dashed"></div>
          <br>
          <h6 class="text-uppercase text-black-50 mb-1"> Products Details</h6>
          <div class="form-row d-none d-md-flex">
            <div class="col-8">
              <div class="form-group mb-0">
                <label>Warehouse Name</label>
              </div>
            </div>
            <div class="col-2">
              <div class="form-group mb-0">
                <label> Threshold</label>
              </div>
            </div>
            <div class="col-2">
              <div class="form-group mb-0">
                <label>Item Count</label>
              </div>
            </div>
          </div>
          <% if @product.warehouse_products.present? %>
            <%= f.fields_for :warehouse_products, f.object.warehouse_products, wrapper_tag: :div do |row| %>
              <div class="error list-group disabled align-center text-danger mb-0 px-1"></div>
              <div class="form-row flex-row align-items-start">
                <%= row.hidden_field :product_id %>
                <%= row.hidden_field :warehouse_id %>
                <%#binding.pry %>
                <div class="col-12 col-md-8">
                  <div class="form-group mb-3">
                    <%= row.input :warehouse, input_html: {class: 'form-control', value: row.object.warehouse.name}, readonly: true, label: false %>
                  </div>
                </div>
                <div class="col-12 col-md-2">
                  <%= row.input :threshold, input_html: {class: 'form-control', value: row.object.threshold}, label: false %>
                </div>
                <div class="col-2 col-md-2">
                  <%= row.input :item_count, input_html: {class: 'form-control', value: row.object.item_count}, label: false %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="card-footer">
          <div class="form-row">
            <%= button_tag(type: "submit", class: "btn btn-dark btn-color btn-block") do %>
              <i class="fal fa-pen"></i> Update
            <% end %>
          </div>
        </div>
      </div>

    <% end %>
  </section>
</div>

app/views/products/edit.html.erb
<div class="col-12 mt-5">
  <%= simple_form_for([@product], url: product_path(@product.id)) do |f| %>
    <%= render 'shared/snippets/form_errors', f: f %>


    <div class="card">
      <div class="card-header mt-4">
        <div class="page-header text-center text-black-50">
          <h2>Products Edit</h2>
        </div>
      </div>

      <div class="card-body">
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.input :sku_code, input_html: {class: 'form-control'} %>
          </div>
          <div class="form-group col-md-6">
            <%= f.input :name, input_html: {class: 'form-control'} %>
          </div>
        </div>
        <div class="form-group">
          <%= f.input :price, input_html: {class: 'form-control'}, value: action_name == 'edit' ? f.object.price : 0 %>
        </div>
        <br>
        <div class="border-dashed"></div>
        <br>
        <h6 class="text-uppercase text-black-50 mb-1"> Products Details</h6>
        <div class="form-row d-none d-md-flex">
          <div class="col-8">
            <div class="form-group mb-0">
              <label>Warehouse Name</label>
            </div>
          </div>
          <div class="col-2">
            <div class="form-group mb-0">
              <label> Threshold</label>
            </div>
          </div>
          <div class="col-2">
            <div class="form-group mb-0">
              <label>Item Count</label>
            </div>
          </div>
        </div>
        <% if @product.warehouse_products.present? %>
          <%= f.fields_for :warehouse_products, f.object.warehouse_products, wrapper_tag: :div do |row| %>
            <%= render 'shared/snippets/form_errors', f: f %>
            <div class="form-row flex-row align-items-start">
              <%= row.hidden_field :product_id %>
              <%= row.hidden_field :warehouse_id %>
              <%#binding.pry %>
              <div class="col-12 col-md-8">
                <div class="form-group mb-3">
                <%= row.input :warehouse, input_html: {class: 'form-control', value: row.object.warehouse.name }, readonly: true, label: false %>
                </div>
              </div>
              <div class="col-12 col-md-2">
                <%= row.input :threshold, input_html: {class: 'form-control', value: row.object.threshold }, label: false %>
              </div>
              <div class="col-2 col-md-2">
                <%= row.input :item_count, input_html: { class: 'form-control', value: row.object.item_count }, label: false %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="card-footer">
        <div class="form-row">
          <%= button_tag(type: "submit", class: "btn btn-dark btn-block") do %>
            <i class="fal fa-pen"></i> Update
          <% end %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/products/index.html.erb
<div class="col-lg-12 mt-1">
      <table class="datatable table table-bordered table-striped table-hover dt-responsive wrap-whitespace w-100 h-auto" data-fixed-header="false">
        <h3 class="sub-header text-center mt-4">Product Wise List</h3>
        <thead>
                <tr>
                  <th class="no-sort">ID</th>
                  <th class="no-sort">Sku Code</th>
                  <th class="border-right">Product Name</th>
                  <% @warehouses.all.each do |w| %>
                  <th><%= w.name %></th>
                    <th>Item Count</th>
                    <th class="border-right">Threshold</th>
                  <% end %>
                </tr>

        </thead>
        <tbody>
        <% @products.each_with_index do |product, index| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= link_to (product.sku_code), edit_product_path(product.id) %></td>
            <td><%= product.name %></td>
            <% product.warehouse_products.each_with_index do |row, index| %>
              <td> <%= link_to (row.warehouse.name), warehouse_path(row.warehouse_id) %> </td>
              <td class="font-weight-bold " style="font-size:20px;"><%= status_badge(row.item_count) %></td>
              <td><%= row.threshold %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="container pagination justify-content-center">
      <%= paginate @products %>
    </div>
  </div>
</div>

app/views/shared/snippets/_form_errors.html.erb
<% if f.object.errors.any? %>
  <ul class="list-group text-danger mb-3">
    <% f.object.errors.full_messages.each do |message| %>
      <li class="list-group-item"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/snippets/_search.html.erb
<%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'navbar-form navbar-mr-auto form-inline my-2 my-lg-0' } do |f| %>
  <%= f.input :name, input_html: {class: "form-control mr-sm-2", value: "", placeholder: "Search"}, label: false %>
  <%= f.submit "Search", class: "btn btn-outline-warning my-2 my-sm-0" %>
<% end %>

app/views/warehouse_products/index.html.erb
<div class="col-lg-12">
  <div class="card mt-5">
    <div class="card-body">
      <table class="datatable table table-bordered table-striped table-hover dt-responsive wrap-whitespace w-100" data-fixed-header="false">
        <h4 class="sub-header text-center text-black-70 mt-4">Product List Page</h4>
        <thead>
        <tr>
          <th class="no-sort">Sr. NO</th>
          <th class="sort">Sku Code</th>
          <th class="no-sort">Product Name</th>
          <th class="no-sort">Warehouse</th>
          <th class="sort">Product Count</th>
        </tr>
        </thead>
        <tbody>
        <% @warehouse_products.each_with_index do |product, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= link_to (product.product.sku_code), edit_product_path(product.product.id) %></td>
            <td><%= product.to_s %></td>
            <td><%= product.warehouse.name %></td>
            <td><%= status_badge(product.item_count) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="container pagination justify-content-center" >
    <%= paginate @warehouse_products %>
    </div>
  </div>
</div>

app/views/warehouses/_form.html.erb
<div class="col-10 mt-5">
  <section class="mb-3 pt-3 pt-lg-5 pb-2">
  <%= simple_form_for([@warehouse]) do |f| %>
    <%= render 'shared/snippets/form_errors', f: f %>

      <div class="alert alert-info alert-dismissible fade show">
      <strong>Info!</strong> Creating New warehouse will add existing all Products to this Warehouse
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>
    <div class="card">
      <div class="card-header">
        <div class="page-header text-center text-black-50">
          <h2 class="font-weight-bold">Warehouse New</h2>
        </div>
      </div>

      <div class="card-body">
        <div class="error list-group disabled align-center text-danger mb-0 px-1"></div>
        <div class="form-row">
          <div class="form-group col-md-12">
            <%= f.input :wh_code, input_html: {class: 'form-control'}, label: 'Warehouse Code' %>
          </div>
          <div class="form-group col-md-12">
            <%= f.input :name, input_html: {class: 'form-control'} %>
          </div>
          <div class="form-group col-md-12">
            <%= f.input :pincode, input_html: {class: 'form-control'} %>
          </div>
          <div class="form-group col-md-12">
            <%= f.input :max_capacity, input_html: {class: 'form-control'} %>
          </div>
        </div>
      </div>

      <div class="card-footer">
        <div class="form-row">
          <%= f.button :submit, class: "btn btn-dark btn-color btn-block"%>
        </div>
      </div>
    </div>
  <% end %>
  </section>
</div>

app/views/warehouses/edit.html.erb
<%= render 'form' %>

app/views/warehouses/index.html.erb
<div class="col-lg-12">
  <div class="card mt-5">
    <div class="card-body">
      <table class="datatable table table-bordered table-striped table-hover dt-responsive wrap-whitespace w-100" data-fixed-header="false">
        <h4 class="sub-header text-center text-black-50 mt-4">Warehouse List</h4>
        <thead>
        <tr>
          <th class="no-sort">Sr. NO</th>
          <th class="sort">Wh Code</th>
          <th class="no-sort">warehouse Name</th>
          <th class="no-sort">Max Capacity</th>
          <th class="sort">Total Products</th>
        </tr>
        </thead>
        <tbody>
        <% @warehouses.each_with_index do |warehouse, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= link_to (warehouse.wh_code), warehouse_path(warehouse.id) %></td>
            <td><%= warehouse.name %></td>
            <td><%= warehouse.max_capacity %></td>
            <td><%= warehouse.products.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="container pagination justify-content-center" >
      <%= paginate @warehouses %>
    </div>
  </div>
</div>

app/views/warehouses/new.html.erb
<%= render 'form' %>

app/views/warehouses/show.html.erb
<div class="col-lg-11 ml-lg-5 mt-5 mr-lg-5">
  <div class="card mb-3">
    <div class="card-body">
      <section class="mb-3">
        <div>
          <h6 class="text-uppercase text-black-50 mb-1"> Warehouse Details</h6>
          <div class="form-row mt-2 align-items-center">
            <div class="col-6 col-md-4 mb-2">
              <strong class="d-block">Warehouse #</strong>
              <%= @warehouse.name %>
            </div>
            <div class="col-6 col-md-4 mb-2">
              <strong class="d-block">Warehouse Code#</strong>
              <%= @warehouse.wh_code %>
            </div>
            <div class="col-6 col-md-4 mb-2">
              <%= link_to 'delete', warehouse_path(@warehouse.id), :method => :delete, class: 'btn btn-success' %>
              <%= link_to 'edit', edit_warehouse_path(@warehouse.id), class: 'btn btn-success' %>
            </div>
            <div class="col-6 col-md-4 mb-2">
              <strong class="d-block">Pincode #</strong>
              <%= @warehouse.pincode %>
            </div>
            <div class="col-6 col-md-4 mb-2">
              <strong class="d-block">Threshold #</strong>
              <%= @warehouse.threshold %>
            </div>
            <div class="col-6 col-md-4 mb-2">
              <strong class="d-block">Max Capacity #</strong>
              <%= @warehouse.max_capacity %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
  <div class="card mb-2">
    <div class="card-body">
      <div class="d-md-flex text-black-50 justify-content-between mb-1">
        <h6 class="display-5 mb-1">Product Stock</h6>
      </div>
      <table class="datatable table table-bordered table-striped table-hover dt-responsive wrap-whitespace w-100" data-fixed-header="false">
        <thead>
        <tr>
          <th class="no-sort">Sr. NO</th>
          <th class="sort">Sku Code</th>
          <th class="no-sort">Product Name</th>
          <th class="sort">Product Count</th>
        </tr>
        </thead>
        <tbody>
        <% @warehouse_products.each_with_index do |product, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= link_to (product.product.sku_code), edit_product_path(product.product.id) %></td>
            <td><%= product.to_s %></td>
            <td><%= status_badge(product.item_count) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="container pagination justify-content-center">
      <%= paginate @warehouse_products %>
    </div>
  </div>
</div>